### PR TITLE
[WIP] Docker-Compose deployment

### PR DESCRIPTION
**Pull request by alysivji**
Thanks for getting me started with your `docker-compose.yml` template. Started filling in some of my preferred practices.

Next step is to expand upon the Dockerfile which builds off jupyterhub. Think I need to create an admin account and install scriptedforms. Will create a volume mount for users to add their markdown documents.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
LGTM so far :+1:

**Comment by alysivji** [comment]
Apologies for dropping off. I settled into a new job and have time to work on open source projects again.

I will have some time over the next few weeks to look into this if you still need a hand.

**Comment by SimonBiggs** [comment]
@alysivji All good :)

I'm trying to decide what is the best way forward for ScriptedForms. Should it look like a Docker based JupyterHub deployment? Or should it look like an electron app?

Does the barrier to entry due to JupyterHub + Docker mean it is better for me to focus efforts on an electron app method instead?

What do you think?

**Comment by alysivji** [comment]
I think JupyterHub is the best model because it is centralized, but getting new technologies deployed at work has always posed a challenge.

I read your post on Reddit. I like the electron app idea, but it loses a lot of the benefit if you have to start sharing files around.

**Comment by SimonBiggs** [comment]
With the electron app it makes me think of using something like a central file server to store the files. It also means each person can tweak their own python if they would like.

I would hope the electron app could be installed just within user space so it won't need admin rights. The plug and play benefits make me think more people would be able to use it.

The other day I was using docker within windows 10 and when my computer restarted it completely stuffed the docker virtual machine. I found this issue on GitHub https://github.com/docker/for-win/issues/573. The solution? Turn the docker VM off, then turn it on again by using an option buried within the docker GUI settings. This fixed my problem, but gee whiz, that issue is 1 year old. And that error message, not helpful.

That moment made me realise that docker is not yet ready to make complicated things simple for people. It doesn't make things simpler, it abstracts things with the trade off of creating hard to diagnose bugs. Docker makes things simpler for people who are already able to scrounge through GitHub issues, however I'm hoping that people who don't even know what GitHub is could download and use ScriptedForms...

So, I really do want ScriptedForms to be "plug and play" with minimal akward bugs. It looks like the docker + jupyterhub just might be a bit much.

I'm certainly happy to be convinced however. I just do need convincing.

**Pull request closed without merging**
